SistemaStock/Areas/Admin/Controllers/EconomatoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SistemaStock.AccesoDatos.Repositorio.IRepositorio;
using SistemaStock.Modelos;
using SistemaStock.Utilidades;
using System.Data;

namespace SistemaStock.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = DS.RoleAdmin)]

    public class EconomatoController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;

        public EconomatoController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo = unidadTrabajo;
        }


        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert (int? id)
        {
            Economato economato = new Economato();
            //Si id null crea una nueva valija
            if(id == null)
            {
                economato.Estado = true;
                return View(economato);
            }
             //Actualizar valija
             economato = await _unidadTrabajo.Economato.Get(id.GetValueOrDefault()); //por si llega null
            if (economato == null)
            {
                return NotFound(); //Por si se manda un id que no existe
            }
            return View(economato);
     
        }


        [HttpPost]
        [ValidateAntiForgeryToken] //Evitar falsificaciones de solicitudes

        public async Task<IActionResult> Upsert(Economato economato)
        {
            if (ModelState.IsValid)
            {
                if(economato.Id == 0)
                {
                    await _unidadTrabajo.Economato.Add(economato);
                    TempData[DS.Exitosa] = "Valija creada correctamente";
                }
                else
                {
                    _unidadTrabajo.Economato.Update(economato);
                    TempData[DS.Exitosa] = "Valija actualizada correctamente";

                }
                await _unidadTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            TempData[DS.Exitosa] = "Error intente nuevamente";
            
            return View(economato);
        }



        #region
        //Llamadas a codigo js

        [HttpGet]

        public async Task<IActionResult> ObtenerTodos()
        {
            var todos = await _unidadTrabajo.Economato.GetAll();
            return Json(new { data = todos });
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var economato = await _unidadTrabajo.Economato.Get(id);
            if(economato == null)
            {
                return Json(new { success = false, message = "Error al borrar valija" });

            }
            _unidadTrabajo.Economato.Remove(economato);
            await _unidadTrabajo.Save();
            return Json(new { success = true, message = "Valija borrada" });
        }



        [ActionName("validarNombre")]
        public async Task <IActionResult> validarNombre(string nombre, int id=0)
        {
            bool valor = false;
            var lista = await _unidadTrabajo.Economato.GetAll();
            if (id == 0)
            {
                valor = lista.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim());
            }
            else
            {
                valor = lista.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim() && b.Id != id);

            }
            if (valor)
            {
                return Json(new { data = true });
            }
            return Json(new { success = false });
        }

        #endregion
    }
}

SistemaStock/Areas/Admin/Controllers/MarcaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SistemaStock.AccesoDatos.Repositorio.IRepositorio;
using SistemaStock.Modelos;
using SistemaStock.Utilidades;
using System.Data;

namespace SistemaStock.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = DS.RoleAdmin)]

    public class MarcaController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;

        public MarcaController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo = unidadTrabajo;
        }


        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert (int? id)
        {
            Marca marca = new Marca();
            //Si id null crea una nueva valija
            if(id == null)
            {
                marca.Estado = true;
                return View(marca);
            }
            //Actualizar valija
            marca = await _unidadTrabajo.Marca.Get(id.GetValueOrDefault()); //por si llega null
            if (marca == null)
            {
                return NotFound(); //Por si se manda un id que no existe
            }
            return View(marca);
     
        }


        [HttpPost]
        [ValidateAntiForgeryToken] //Evitar falsificaciones de solicitudes

        public async Task<IActionResult> Upsert(Marca marca)
        {
            if (ModelState.IsValid)
            {
                if(marca.Id == 0)
                {
                    await _unidadTrabajo.Marca.Add(marca);
                    TempData[DS.Exitosa] = "Marca creada correctamente";
                }
                else
                {
                    _unidadTrabajo.Marca.Update(marca);
                    TempData[DS.Exitosa] = "Categoria actualizada correctamente";

                }
                await _unidadTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            TempData[DS.Exitosa] = "Error intente nuevamente";
            
            return View(marca);
        }



        #region
        //Llamadas a codigo js

        [HttpGet]

        public async Task<IActionResult> ObtenerTodos()
        {
            var todos = await _unidadTrabajo.Marca.GetAll();
            return Json(new { data = todos });
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var marca = await _unidadTrabajo.Marca.Get(id);
            if(marca == null)
            {
                return Json(new { success = false, message = "Error al borrar marca" });

            }
            _unidadTrabajo.Marca.Remove(marca);
            await _unidadTrabajo.Save();
            return Json(new { success = true, message = "Marca borrada" });
        }



        [ActionName("validarNombre")]
        public async Task <IActionResult> validarNombre(string nombre, int id=0)
        {
            bool valor = false;
            var lista = await _unidadTrabajo.Marca.GetAll();
            if (id == 0)
            {
                valor = lista.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim());
            }
            else
            {
                valor = lista.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim() && b.Id != id);

            }
            if (valor)
            {
                return Json(new { data = true });
            }
            return Json(new { success = false });
        }

        #endregion
    }
}

SistemaStock/Areas/Admin/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SistemaStock.AccesoDatos.Repositorio.IRepositorio;
using SistemaStock.Modelos;
using SistemaStock.Modelos.ViewModels;
using SistemaStock.Utilidades;
using System.Data;

namespace SistemaStock.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = DS.RoleAdmin + "," + DS.RoleInventario)]


    public class ProductoController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductoController(IUnidadTrabajo unidadTrabajo, IWebHostEnvironment webHostEnvironment)
        {
            _unidadTrabajo = unidadTrabajo;
            _webHostEnvironment = webHostEnvironment;
        }


        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert (int? id)
        {

            ProductoVM productoVm = new ProductoVM()
            {
                Producto = new Producto(),
                CategoriaLista = _unidadTrabajo.Producto.GetAllDropdownList("Categoria"),
                MarcaLista = _unidadTrabajo.Producto.GetAllDropdownList("Marca")

            };

            if (id == null)
            {
                //Crear producto

                return View (productoVm);
            }
            else
            {
                productoVm.Producto = await _unidadTrabajo.Producto.Get(id.GetValueOrDefault());
                if(productoVm.Producto == null)
                {
                    return NotFound();
                }
                return View(productoVm);

            }
        }


        [HttpPost]
        public async Task<IActionResult> Upsert(ProductoVM productoVM)
        {
            if(ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                string webRootPath = _webHostEnvironment.WebRootPath;


                if (productoVM.Producto.Id == 0 && files.Count >= 3) //Crear producto
                {
                    for (int i = 0; i < 3; i++)
                    {
                        string upLoad = webRootPath + DS.ImagenRut;
                        string fileName = Guid.NewGuid().ToString();
                        string extension = Path.GetExtension(files[0].FileName);
                        using (var fileStream = new FileStream(Path.Combine(upLoad, fileName + extension), FileMode.Create))
                        {
                            files[i].CopyTo(fileStream);
                        }

                        if (i == 0)
                        {
                            productoVM.Producto.ImagenUrl = fileName + extension;
                        }
                        if (i == 1)
                        {
                            productoVM.Producto.ImagenUrlDos = fileName + extension;
                        }
                        if (i == 2)
                        {
                            productoVM.Producto.ImagenUrlTres = fileName + extension;
                        }
                    }
                    await _unidadTrabajo.Producto.Add(productoVM.Producto);

                }
                else
                {
                    //Actualizar
                    var objProducto = await _unidadTrabajo.Producto.GetFirst(p => p.Id == productoVM.Producto.Id, isTracking: false);
                    if (files.Count >= 3)
                    {
                        //Borrar las imagenes anteriores;

                        string upLoad = webRootPath + DS.ImagenRut;
                        BorrarArchivo(upLoad, objProducto.ImagenUrl);
                        BorrarArchivo(upLoad, objProducto.ImagenUrlDos);
                        BorrarArchivo(upLoad, objProducto.ImagenUrlTres);

                        for (int i = 0; i < 3; i++)
                        {

                            string fileName = Guid.NewGuid().ToString();
                            string extension = Path.GetExtension(files[i].FileName);
                            using (var fileStream = new FileStream(Path.Combine(upLoad, fileName + extension), FileMode.Create))
                            {
                                files[i].CopyTo(fileStream);
                            }

                            // Asignar las URLs de las imágenes al producto
                            if (i == 0)
                            {
                                productoVM.Producto.ImagenUrl = fileName + extension;
                            }
                            else if (i == 1)
                            {
                                productoVM.Producto.ImagenUrlDos = fileName + extension;
                            }
                            else if (i == 2)
                            {
                                productoVM.Producto.ImagenUrlTres = fileName + extension;
                            }
                        }
                    } //Caso que no cambie imagen

                    else
                    {
                        productoVM.Producto.ImagenUrl = objProducto.ImagenUrl;
                    }
                    _unidadTrabajo.Producto.Update(productoVM.Producto);
                }

                TempData[DS.Exitosa] = "Exitosa";
                await _unidadTrabajo.Save();
                return View("Index");

            }
            //Si falla
            productoVM.CategoriaLista = _unidadTrabajo.Producto.GetAllDropdownList("Categoria");
            productoVM.MarcaLista = _unidadTrabajo.Producto.GetAllDropdownList("Marca");
            return View(productoVM);
        }


        //Metodo privado para Borrar imagenes 
        private void BorrarArchivo(string directorio, string archivo)
        {
            string rutaArchivo = Path.Combine(directorio, archivo);
            if (System.IO.File.Exists(rutaArchivo))
            {
                System.IO.File.Delete(rutaArchivo);
            }
        }


        #region
        //Llamadas a codigo js

        [HttpGet]

        public async Task<IActionResult> ObtenerTodos()
        {
            var todos = await _unidadTrabajo.Producto.GetAll(incluirPropiedades:"Categoria,Marca");
            return Json(new { data = todos });
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var productoDb = await _unidadTrabajo.Producto.Get(id);
            if(productoDb == null)
            {
                return Json(new { success = false, message = "Error al borrar producto" });

            }

            //Remover imagen
            string upload = _webHostEnvironment.WebRootPath + DS.ImagenRut;
            var anteriorFile = Path.Combine(upload, productoDb.ImagenUrl);
            if (System.IO.File.Exists(anteriorFile))
            {
                System.IO.File.Delete(anteriorFile);
            }

            _unidadTrabajo.Producto.Remove(productoDb);
            await _unidadTrabajo.Save();
            return Json(new { success = true, message = "Producto borrada" });
        }



        [ActionName("validarProducto")]
        public async Task <IActionResult> validarProducto(string numero, int id=0)
        {
            bool valor = false;
            var lista = await _unidadTrabajo.Producto.GetAll();
            if (id == 0)
            {
                valor = lista.Any(b => b.NumeroProducto.ToLower().Trim() == numero.ToLower().Trim());
            }
            else
            {
                valor = lista.Any(b => b.NumeroProducto.ToLower().Trim() == numero.ToLower().Trim() && b.Id != id);

            }
            if (valor)
            {
                return Json(new { data = true });
            }
            return Json(new { success = false });
        }

        #endregion
    }
}

SistemaStock/Areas/Admin/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaStock.AccesoDatos.Data;
using SistemaStock.AccesoDatos.Repositorio.IRepositorio;
using SistemaStock.Utilidades;
using System.Data;

namespace SistemaStock.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = DS.RoleAdmin)]

    public class UsuarioController : Controller
    {

        private readonly IUnidadTrabajo _unidadTrabajo;
        private readonly ApplicationDbContext _db;

        public UsuarioController(IUnidadTrabajo unidadTrabajo, ApplicationDbContext db)
        {
            _unidadTrabajo = unidadTrabajo;
            _db = db;
        }


        public IActionResult Index()
        {
            return View();
        }



        #region API

        [HttpGet]
        public async Task <IActionResult> ObtenerTodos()
        {
            var usuarioLista = await _unidadTrabajo.UsuarioAplicacion.GetAll();
            var userRol = await _db.UserRoles.ToListAsync();
            var roles = await _db.Roles.ToListAsync();

            foreach (var usuario in usuarioLista)
            {
                var roleId = userRol.FirstOrDefault(u => u.UserId == usuario.Id).RoleId;
                usuario.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;
            }
            return Json(new { data = usuarioLista });
        }

        #endregion
    }
}

SistemaStock/Views/Shared/_BtnAddBack.cshtml
<div class="d-grid gap-2 d-md-block">
    <button class="btn btn-primary" type="submit" onfocus="flase"><i class="bi bi-pluse-square-fill"></i>Crear</button>
    <a asp-action="Index" class="btn btn-success"> <i class="bi bi-arrow-return-left">Regresar</i></a>
</div>

SistemaStock/Views/Shared/_BtnUpdateBack.cshtml
@model int

<div class="d-grid gap-2 d-md-block">
    <button class="btn btn-primary" type="submit" onfocus="flase" asp-route-id="@Model"><i class="bi bi-pencil-square"></i>Guardar</button>
    <a asp-action="Index" class="btn btn-success"> <i class="bi bi-arrow-return-left"></i>Regresar</a>
</div>

SistemaStock/Views/Shared/_Layout.cshtml
@using SistemaStock.Utilidades

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaStock</title>
    <link rel="shortcut icon" href="~/imagenes/sistemaStock.jpg"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaStock.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link href="~/lib/select2-bootstrap-5-theme/select2-bootstrap-5-theme.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Index"><img class="img-fluid imgTam" src="~/imagenes/sistemastock.jpg" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Productos</a>

                        </li>


                        @if (User.IsInRole(DS.RoleAdmin) || User.IsInRole(DS.RoleInventario))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" data-bs-toggle="dropdown" aria-expanded="false">Contenido</a>

                                <ul class="dropdown-menu">
                                    @if (User.IsInRole(DS.RoleAdmin))
                                    {
                                        <li> <a class="dropdown-item" asp-area="Admin" asp-controller="Economato" asp-action="Index">Economato</a></li>
                                        <li> <a class="dropdown-item" asp-area="Admin" asp-controller="Categoria" asp-action="Index">Categorias</a></li>
                                        <li> <a class="dropdown-item" asp-area="Admin" asp-controller="Marca" asp-action="Index">Marcas</a></li>
                                    }
                                   
                                    <li> <a class="dropdown-item" asp-area="Admin" asp-controller="Producto" asp-action="Index">Productos</a></li>
                                </ul>
                            </li>
                        }

                        @if (User.IsInRole(DS.RoleAdmin))
                        {
                            <li class="nav-item"> <a class="nav-link text-dark" asp-area="Admin" asp-controller="Usuario" asp-action="Index">Usuarios</a></li>

                        }

                        @if (User.IsInRole(DS.RoleAdmin) || User.IsInRole(DS.RoleInventario))
                        {
                            <li class="nav-item"> <a class="nav-link text-dark" asp-area="Inventario" asp-controller="Factura" asp-action="Index">Stock</a></li>

                        }



                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification"></partial>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted mt-5">
        <div class="container ">
            &copy; 2023 - SistemaStock - <a asp-area=""class="text-decoration-none" asp-controller="Home" asp-action="Privacy"><strong>Mateo Bertoni & Gonzalo Pereira</strong></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>


    <script src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SistemaStock/Views/Shared/_Notification.cshtml
@using SistemaStock.Utilidades

@if (TempData[DS.Exitosa] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[DS.Exitosa]')
    </script>

}

@if (TempData[DS.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[DS.Error]')
    </script>

}